done
ilyatsv/ITIROD pull request #1
Opened 2021-03-18 19:18 UTC by ilyatsv

2021-03-22 19:10 UTC, gmltA requested changes
It's not quite clear to me how do you recover message history upon app crash and following reconnection.

2021-03-22 19:10 UTC, gmltA commented on ITIROD_1lab/ITIROD_1lab/Program.cs
> +                    Thread receiveThread = new Thread(new ThreadStart(ReceiveMessage));
This is the second place you create `receiveThread`. What for?

2021-03-22 19:44 UTC, ilyatsv commented on ITIROD_1lab/ITIROD_1lab/Program.cs
> +                    Thread receiveThread = new Thread(new ThreadStart(ReceiveMessage));
Я использую singleton user в котором находится коллекция чатов. А насчет потока. Если я не уничтожаю старый поток -  сообщения уходят в никуда т.к. я закрыл receiver в нем , из-за чего я не получаю сообщения.

2021-03-22 19:48 UTC, gmltA commented on ITIROD_1lab/ITIROD_1lab/Program.cs
> +                    Thread receiveThread = new Thread(new ThreadStart(ReceiveMessage));
Гэта не здымае майго пытання: навошта вам 2 thread'а для прыёма паведамленняў. Калі вы нешта губляеце, ёсць амаль 100% верагоднасць, што вы няверна працуеце з патокамі.

2021-03-22 19:57 UTC, ilyatsv commented on ITIROD_1lab/ITIROD_1lab/Program.cs
> +                    Thread receiveThread = new Thread(new ThreadStart(ReceiveMessage));
Я создаю 1 поток для 1 чата . Как только я выхожу из чата - закрываю поток. В таком случае у меня всегда один поток принимающий сообщения .

2021-03-22 20:02 UTC, gmltA commented on ITIROD_1lab/ITIROD_1lab/Program.cs
> +                    Thread receiveThread = new Thread(new ThreadStart(ReceiveMessage));
Я ўсё яшчэ не разумею, навошта вам паток і ўнутры карыстальніка, і ў main...

2021-03-22 20:05 UTC, ilyatsv commented on ITIROD_1lab/ITIROD_1lab/Program.cs
> +                    Thread receiveThread = new Thread(new ThreadStart(ReceiveMessage));
А это я криво написал , у меня и main и enter() делают одно и тоже просто main нельзя вызвать из другой функции вот я и продублировал.

2021-03-25 19:34 UTC, gmltA commented
Калі можна будзе глядзець, запрасіце review нанава.

2021-03-26 20:31 UTC, gmltA approved these changes

2021-03-26 20:48 UTC, merged