TrelloAlikeApp
ilyatsv/ITIROD pull request #3
Opened 2021-05-08 17:12 UTC by ilyatsv

2021-05-11 12:42 UTC, gmltA requested changes

2021-05-11 12:42 UTC, gmltA commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/authentication/login.html
> +                    <button onclick="window.location.href = 'https://vk.com';" class="button_vk"/>
How's that a button?

2021-05-11 12:42 UTC, gmltA commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/authentication/login.html
> +            <button class="button " onclick="location.href='login.html'">Login</button>
This is not a `button`.

2021-05-11 12:42 UTC, gmltA commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/boards/add-edit-board.html
> +            <div class="board-form">
You have two nested elements with the same class. Is it ok?

2021-05-11 12:42 UTC, gmltA commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/boards/board.html
> +                        <p class>02.03.2021</p>
There's a better HTML tag for such content.

2021-05-11 12:42 UTC, gmltA commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/boards/board.html
> +                            <i class="fa fa-trash" aria-hidden="true"></i>
What's `aria-hidden` here?

2021-05-16 17:56 UTC, ilyatsv commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/boards/board.html
> +                            <i class="fa fa-trash" aria-hidden="true"></i>
![image](https://user-images.githubusercontent.com/62513791/118407369-27d55800-b689-11eb-867d-fa4633c73907.png)

2021-05-18 19:34 UTC, gmltA commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/boards/board.html
> +                            <i class="fa fa-trash" aria-hidden="true"></i>
Indeed. Turnes out you don't have any accessible content in button. What will you say to that?

2021-05-18 19:37 UTC, gmltA reviewed
That's a <kbd>8</kbd> after you answer my question.

2021-05-20 21:02 UTC, ilyatsv commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/boards/board.html
> +                            <i class="fa fa-trash" aria-hidden="true"></i>
Иконка является декоративной . А aria-hidden = true обеспечивает нечитаемость для приложений. читающих вслух.

2021-05-26 19:58 UTC, gmltA commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/boards/board.html
> +                            <i class="fa fa-trash" aria-hidden="true"></i>
І ў вас пустая кнопка без аніякага тлумачэння дзеяння, якое адбудзецца пры кліке на яе. Раз вырашылі капіраваць незразумела код аднекуль, зараз зрабіце так, каб тэкст у кнопке чытался screen-reader'ом, але быў нябачны.

2021-05-29 14:47 UTC, gmltA requested changes

2021-05-29 14:47 UTC, gmltA commented on TrelloAlikeApp/TrelloAlikeApp/TrelloAlikeApp/boards/board.html
>                          <p class>02.03.2021</p>
А гэта выправіць?

2021-06-01 18:43 UTC, gmltA approved these changes

2021-06-02 09:29 UTC, merged